### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by dreme** [mauhai/awesome-jupyterlab#15]
I can't seem to install the awesome-jupyterlab extension. I'm getting an error message which says that "awesome-jupyterlab" is not a valid npm package.

Here's a copy of my terminal installation command and output (linux Mint 19):
```
(base) vitas@vitas-Mint19:~$ jupyter labextension install awesome-jupyterlab
Node v11.14.0

> /home/vitas/anaconda3/bin/npm pack awesome-jupyterlab
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/awesome-jupyterlab - Not found
npm ERR! 404 
npm ERR! 404  'awesome-jupyterlab@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vitas/.npm/_logs/2019-06-19T04_16_39_031Z-debug.log

Errored, use --debug for full output:
ValueError: "awesome-jupyterlab" is not a valid npm package

```

**Comment by mvoelske** [comment]
As far as I can tell, there is no `awesome-jupyterlab` extension. You'll have to install the extensions mentioned in [Readme.me](https://github.com/mauhai/awesome-jupyterlab/blob/master/README.md) individually.

**Comment by dreme** [comment]
Oh, I see.  I misunderstood that `awesome-jupyterlab` was a 'meta' extension which installed all of the listed extensions in this GIT
